// global variable
const resultBox = document.getElementsByClassName('result')[0];
const generateButton = document.getElementById('generate');
const uppercase = document.getElementById('uppercase');
const lowercase = document.getElementById('lowercase');
const number = document.getElementById('number');
const special = document.getElementById('special');
const passwordLength = document.getElementById('passwordLength');

// to store password options
let passwordOption = [];
let passwordlengthOption = [];

// api
const apiURL = 'http://localhost:6968/password/';

/**
 * This function will hides the resultbox when dom load
 */
function hideResultBoxOnDomLoad() {
    window.addEventListener('DOMContentLoaded', (event) => {
        resultBox.style.background = 'white';
        resultBox.innerHTML = '‏‎ ‎‏‎ ‎‏‎ ‎‏‎ ‎‏‎ ‎‏‎ ‎‏‎ ‎';
    });
}

/**
 * This function will spit out geneated text into result box
 * @param {String} input
 */
function showResultBox(input) {
    resultBox.style.background = '#e8e8e7';
    resultBox.innerHTML = input;
}

/**
 * This function will get value when user have checked the password
 * options and push it into an array above
 * @param {Object} option
 */
function getPasswordCheckboxValue(option) {
    if (option.checked == true) {
        passwordOption.push(option.value);
    } else {
        const pass = passwordOption.filter((pass) => pass != option.value);
        passwordOption = pass;
    }
}

/**
 * This function returns the lenght of an password
 * @returns {Number}
 */
function getPasswordLengthValue() {
    const length = Number.parseInt(passwordLength.value); // convert
    passwordlengthOption.push(length);
    passwordlengthOption = passwordlengthOption.slice(passwordlengthOption.length - 1);
    return passwordlengthOption[passwordlengthOption.length - 1];
}

/**
 * This function will returns user input options into api url
 * @returns {String} Example: http://localhost:3000/20/uppercase
 */
function getUserInputIntoAPIURL() {
    const length = getPasswordLengthValue();
    const params = passwordOption.join('/');
    return `${apiURL}${length}/${params}`;
}

/**
 * This function will request api generated by user into an actualy api
 * and spit ot the text into text
 */
function generate() {
    // btn 'generate' click
    generateButton.addEventListener('click', () => {
        const passwordAPI = getUserInputIntoAPIURL();
        fetch(passwordAPI)
            .then((res) => res.json())
            .then((res) => {
                const { password } = res;
                showResultBox(password);
            })
            .catch();
    });
}

// -------------------- main -------------------
(function main() {
    hideResultBoxOnDomLoad();
    generate();
})();
